
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FakeBank.Data.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Account
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Account()
    {

        this.Transactions = new HashSet<Transaction>();

        this.Transactions1 = new HashSet<Transaction>();

    }


    public System.Guid Id { get; set; }

    public System.DateTime BeginDate { get; set; }

    public double Balance { get; set; }

    public System.Guid IdAccountType { get; set; }

    public string IdCustomer { get; set; }

    public bool Active { get; set; }



    public virtual AccountType AccountType { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }

    public virtual Token Token { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transaction> Transactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transaction> Transactions1 { get; set; }

    public virtual Card Card { get; set; }

}

}
