//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeBank.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public System.Guid Id { get; set; }
        public string Nip { get; set; }
        public string ExpirationDate { get; set; }
        public int SecurityCode { get; set; }
        public int CardType { get; set; }
        public string CardNumber { get; set; }
        public bool Active { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
