//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeBank.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public System.Guid id { get; set; }
        public string nip { get; set; }
        public System.DateTime expirationDate { get; set; }
        public int securityCode { get; set; }
        public int cardType { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
