//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeBank.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreRegistration
    {
        public System.Guid id { get; set; }
        public string username { get; set; }
        public string firstLastName { get; set; }
        public string secondLastName { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
    }
}
